name: ROMM
slug: romm_dev
version: "1.0.4"
description: Retro ROM Manager
arch:
  - amd64

startup: services
boot: auto
init: false

options:
  romm_auth_secret_key: "replace_with_long_random_secret"
  database_url: "sqlite:////config/romm.db"

schema:
  romm_auth_secret_key: str
  database_url: str

map:
  - share:rw
  - config:rw

ports:
  8080/tcp: 8080

webui: http://[HOST]:[PORT:8080]
