name: ROMM
slug: romm
version: "1.0.1"
description: Retro ROM Manager for HA
arch:
  - amd64

startup: services
boot: auto
init: false

# HA add-on options
options:
  romm_auth_secret_key: "supersecretkey123"
  database_url: "sqlite:////config/romm.db"

schema:
  romm_auth_secret_key: str
  database_url: str

map:
  - share:rw
  - config:rw

ports:
  8080/tcp: 8080

command: ["/run.sh"]

webui: http://[HOST]:[PORT:8080]
